### ISSUE TITLE
Konveyor kiosk demo

### ISSUE THREAD

**Issue by savitharaghunathan** [konveyor/community#48]
```[tasklist]
### Tasks
- [x] @rromannissen - Brainstorm on the ~90s video content - https://drive.google.com/drive/u/0/folders/1O2xvEtxO2kRfPiMdtCKz6sepLCvLuvhc
- [x] @rromannissen @dymurray @jwmatthews  - Roadmap content for Konveyor
- [x] @djzager - Help with video content editing - https://drive.google.com/file/d/1LssFrG1e1vqenVRJ_1o9Pl5Ryu6rTR17/view?usp=share_link
- [x] @savitharaghunathan - local demo - https://github.com/konveyor/example-applications/tree/main/example-1
```

```[tasklist]
### Optional Tasks
- [ ] @pranavgaikwad @shawn-hurley - Get a few Analyzers demo up on the youtube, if possible with CC/voice over
- [ ] @savitharaghunathan @shawn-hurley - 20 min demo
```

All: If anyone want in/off of the task items, let me know.
