### ISSUE TITLE
Konveyor Kiosk NA 2023

### ISSUE THREAD

**Issue by savitharaghunathan** [konveyor/community#63]
```[tasklist]
### Tasks
- [ ] 90s video - @rromannissen @djzager 
- [ ] Roadmap slides - @savitharaghunathan 
- [ ] QR code with Konveyor resources - @savitharaghunathan 
- [ ] Kantra demo - @eemcmullan 
- [ ] Konveyor demo - extended version of the 90s video
```
